services:
    oro_api.get_config.processor:
        class: Oro\Bundle\ApiBundle\Processor\Config\ConfigProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - get_config

    oro_api.get_config.load_from_config_bag:
        class: Oro\Bundle\ApiBundle\Processor\Config\GetConfig\LoadFromConfigBag
        arguments:
            - @oro_api.config_bag
        tags:
            - { name: oro.api.processor, action: get_config, priority: -10 }

    oro_api.get_config.load_from_metadata:
        class: Oro\Bundle\ApiBundle\Processor\Config\GetConfig\LoadFromMetadata
        arguments:
            - @oro_api.build_config.processor
        tags:
            - { name: oro.api.processor, action: get_config, priority: -20 }

    oro_api.get_config.normalize_definition:
        class: Oro\Bundle\ApiBundle\Processor\Config\GetConfig\NormalizeDefinition
        arguments:
            - @oro_api.doctrine_helper
            - @oro_api.field_config_provider
            - @oro_api.relation_config_provider
            - @oro_api.entity_exclusion_provider
        tags:
            - { name: oro.api.processor, action: get_config, priority: -30 }

    oro_api.get_config.normalize_filters:
        class: Oro\Bundle\ApiBundle\Processor\Config\GetConfig\NormalizeFilters
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get_config, requestAction: get_list, priority: -30 }
