services:
    oro_api.get.processor:
        class: Oro\Bundle\ApiBundle\Processor\GetProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - get
        tags:
            - { name: oro.api.action_processor }


    #
    # initialize
    #
    oro_api.get.initialize_criteria:
        class: Oro\Bundle\ApiBundle\Processor\Shared\InitializeCriteria
        arguments:
            - @oro_entity.orm.entity_class_resolver
        tags:
            - { name: oro.api.processor, action: get, group: initialize, priority: 250 }

    oro_api.get.normalize_version:
        class: Oro\Bundle\ApiBundle\Processor\Shared\NormalizeVersion
        tags:
            - { name: oro.api.processor, action: get, group: initialize, priority: 250 }

    oro_api.get.normalize_include_header:
        class: Oro\Bundle\ApiBundle\Processor\Shared\NormalizeIncludeHeader
        tags:
            - { name: oro.api.processor, action: get, group: initialize, priority: 50 }

    oro_api.get.normalize_entity_class:
        class: Oro\Bundle\ApiBundle\Processor\Shared\NormalizeEntityClass
        arguments:
            - @oro_api.value_normalizer
        tags:
            - { name: oro.api.processor, action: get, group: initialize, priority: 20 }

    oro_api.get.normalize_entity_id:
        class: Oro\Bundle\ApiBundle\Processor\Shared\Rest\NormalizeEntityId
        arguments:
            - @oro_api.doctrine_helper
            - @oro_api.value_normalizer
        tags:
            - { name: oro.api.processor, action: get, group: initialize, requestType: rest, priority: 10 }

    oro_api.get.load_config:
        class: Oro\Bundle\ApiBundle\Processor\Get\LoadConfig
        arguments:
            - @oro_api.config_provider
        tags:
            - { name: oro.api.processor, action: get, group: initialize, priority: -20 }

    #
    # security_check
    #

    oro_api.get.entity_type_security_check:
        class: Oro\Bundle\ApiBundle\Processor\Shared\EntityTypeSecurityCheck
        arguments:
            - @security.authorization_checker
            - @oro_api.doctrine_helper
            - VIEW
        tags:
            - { name: oro.api.processor, action: get, group: security_check, priority: 10 }

    #
    # build_query
    #

    oro_api.get.complete_criteria:
        class: Oro\Bundle\ApiBundle\Processor\Shared\CompleteCriteria
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get, group: build_query, priority: -50 }

    oro_api.get.protect_query_by_acl:
        class: Oro\Bundle\ApiBundle\Processor\Shared\ProtectQueryByAcl
        arguments:
            - @oro_security.acl_helper
            - VIEW
        tags:
            - { name: oro.api.processor, action: get, group: build_query, priority: -90 }

    oro_api.get.build_query:
        class: Oro\Bundle\ApiBundle\Processor\Get\BuildQuery
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get, group: build_query, priority: -100 }

    #
    # load_data
    #

    oro_api.get.load_data_by_entity_serializer:
        class: Oro\Bundle\ApiBundle\Processor\Get\LoadDataByEntitySerializer
        arguments:
            - @oro_api.entity_serializer
        tags:
            - { name: oro.api.processor, action: get, group: load_data, priority: -10 }

    oro_api.get.load_data_by_orm_query:
        class: Oro\Bundle\ApiBundle\Processor\Get\LoadDataByOrmQuery
        tags:
            - { name: oro.api.processor, action: get, group: load_data, priority: -20 }

    #
    # normalize_data
    #

    oro_api.get.initialize_entity_proxy:
        class: Oro\Bundle\ApiBundle\Processor\Get\InitializeEntityProxy
        tags:
            - { name: oro.api.processor, action: get, group: normalize_data, priority: 10 }

    oro_api.get.normalize_data:
        class: Oro\Bundle\ApiBundle\Processor\Get\NormalizeData
        arguments:
            - @oro_api.item_normalizer
        tags:
            - { name: oro.api.processor, action: get, group: normalize_data, priority: -10 }

    #
    # finalize
    #

    oro_api.get.validate_result:
        class: Oro\Bundle\ApiBundle\Processor\Get\ValidateResult
        tags:
            - { name: oro.api.processor, action: get, group: finalize, priority: 250 }
