services:
    oro_api.normalize_value.processor:
        class: Oro\Bundle\ApiBundle\Processor\NormalizeValueProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - normalize_value

    #
    # common processors
    #

    oro_api.normalize_value.integer:
        class: Oro\Bundle\ApiBundle\Processor\NormalizeValue\NormalizeInteger
        tags:
            - { name: oro.api.processor, action: normalize_value, dataType: integer, priority: -10 }

    oro_api.normalize_value.unsigned_integer:
        class: Oro\Bundle\ApiBundle\Processor\NormalizeValue\NormalizeUnsignedInteger
        tags:
            - { name: oro.api.processor, action: normalize_value, dataType: unsignedInteger, priority: -10 }

    oro_api.normalize_value.entity_alias:
        class: Oro\Bundle\ApiBundle\Processor\NormalizeValue\NormalizeEntityAlias
        arguments:
            - @oro_entity.entity_alias_resolver
        tags:
            - { name: oro.api.processor, action: normalize_value, dataType: entityAlias, priority: -10 }

    oro_api.normalize_value.entity_plural_alias:
        class: Oro\Bundle\ApiBundle\Processor\NormalizeValue\NormalizeEntityPluralAlias
        arguments:
            - @oro_entity.entity_alias_resolver
        tags:
            - { name: oro.api.processor, action: normalize_value, dataType: entityPluralAlias, priority: -10 }

    #
    # REST API processors
    #

    oro_api.normalize_value.rest_json_api.boolean:
        class: Oro\Bundle\ApiBundle\Processor\NormalizeValue\RestJsonApi\NormalizeBoolean
        tags:
            - { name: oro.api.processor, action: normalize_value, requestType: rest_json_api, dataType: boolean, priority: -10 }

    oro_api.normalize_value.rest_json_api.datetime:
        class: Oro\Bundle\ApiBundle\Processor\NormalizeValue\RestJsonApi\NormalizeDateTime
        tags:
            - { name: oro.api.processor, action: normalize_value, requestType: rest_json_api, dataType: datetime, priority: -10 }

    oro_api.normalize_value.rest_json_api.order_by:
        class: Oro\Bundle\ApiBundle\Processor\NormalizeValue\RestJsonApi\NormalizeOrderBy
        tags:
            - { name: oro.api.processor, action: normalize_value, requestType: rest_json_api, dataType: orderBy, priority: -10 }
