services:
    oro_api.get_config.processor:
        class: Oro\Bundle\ApiBundle\Processor\GetConfigProcessor
        public: false
        arguments:
            - @oro_api.processor_bag

    oro_api.get_config.config:
        class: Oro\Bundle\ApiBundle\Processor\GetConfig\GetConfig
        arguments:
            - @oro_api.config_bag
        tags:
            - { name: oro.api.processor, action: get_config, priority: -10 }

    oro_api.get_config.metadata:
        class: Oro\Bundle\ApiBundle\Processor\GetConfig\GetConfigFromMetadata
        arguments:
            - @oro_api.build_config.processor
        tags:
            - { name: oro.api.processor, action: get_config, priority: -20 }
