services:
    oro_api.get_metadata.processor:
        class: Oro\Bundle\ApiBundle\Processor\MetadataProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - get_metadata

    oro_api.get_metadata.load_entity_metadata:
        class: Oro\Bundle\ApiBundle\Processor\GetMetadata\LoadEntityMetadata
        arguments:
            - @oro_api.doctrine_helper
            - @oro_api.entity_metadata_factory
        tags:
            - { name: oro.api.processor, action: get_metadata, priority: -10 }

    oro_api.get_metadata.normalize_metadata:
        class: Oro\Bundle\ApiBundle\Processor\GetMetadata\NormalizeMetadata
        tags:
            - { name: oro.api.processor, action: get_metadata, priority: -50 }

    oro_api.get_metadata.normalize_entity_metadata:
        class: Oro\Bundle\ApiBundle\Processor\GetMetadata\NormalizeEntityMetadata
        arguments:
            - @oro_api.doctrine_helper
            - @oro_api.entity_metadata_factory
        tags:
            - { name: oro.api.processor, action: get_metadata, priority: -60 }
