services:
    oro_api.build_config.processor:
        class: Oro\Bundle\ApiBundle\Processor\Config\ConfigProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - build_config

    oro_api.get_config.processor:
        class: Oro\Bundle\ApiBundle\Processor\Config\ConfigProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - get_config

    oro_api.get_field_config.processor:
        class: Oro\Bundle\ApiBundle\Processor\Config\FieldConfigProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - get_field_config

    oro_api.get_relation_config.processor:
        class: Oro\Bundle\ApiBundle\Processor\Config\RelationConfigProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - get_relation_config

    #
    # build_config
    #

    oro_api.build_config.definition:
        class: Oro\Bundle\ApiBundle\Processor\Config\BuildConfig\BuildDefinition
        tags:
            - { name: oro.api.processor, action: build_config, priority: -10 }

    oro_api.build_config.filters:
        class: Oro\Bundle\ApiBundle\Processor\Config\BuildConfig\BuildFilters
        tags:
            - { name: oro.api.processor, action: build_config, configSection: filters, priority: -10 }

    #
    # get_config
    #

    oro_api.get_config.load_from_config_bag:
        class: Oro\Bundle\ApiBundle\Processor\Config\GetConfig\LoadFromConfigBag
        arguments:
            - @oro_api.config_bag
        tags:
            - { name: oro.api.processor, action: get_config, priority: -10 }

    oro_api.get_config.load_from_metadata:
        class: Oro\Bundle\ApiBundle\Processor\Config\GetConfig\LoadFromMetadata
        arguments:
            - @oro_api.build_config.processor
        tags:
            - { name: oro.api.processor, action: get_config, priority: -20 }

    #
    # get_field_config
    #

    oro_api.get_field_config.load_from_metadata:
        class: Oro\Bundle\ApiBundle\Processor\Config\GetFieldConfig\LoadFromMetadata
        tags:
            - { name: oro.api.processor, action: get_field_config, priority: -20 }

    #
    # get_relation_config
    #

    oro_api.get_relation_config.load_from_config_bag:
        class: Oro\Bundle\ApiBundle\Processor\Config\GetRelationConfig\LoadFromConfigBag
        arguments:
            - @oro_api.config_bag
            - @oro_entity.entity_hierarchy_provider.all
        tags:
            - { name: oro.api.processor, action: get_relation_config, priority: -10 }

    oro_api.get_relation_config.load_from_metadata:
        class: Oro\Bundle\ApiBundle\Processor\Config\GetRelationConfig\LoadFromMetadata
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get_relation_config, priority: -20 }

    #
    # config normalization
    #

    oro_api.get_relation_config.normalize_definition:
        class: Oro\Bundle\ApiBundle\Processor\Config\Shared\NormalizeDefinition
        arguments:
            - @oro_api.doctrine_helper
            - @oro_api.field_config_provider
            - @oro_api.relation_config_provider
            - @oro_api.entity_exclusion_provider
        tags:
            - { name: oro.api.processor, action: get_config, priority: -50 }
            - { name: oro.api.processor, action: get_field_config, priority: -50 }
            - { name: oro.api.processor, action: get_relation_config, priority: -50 }

    oro_api.get_relation_config.normalize_filters:
        class: Oro\Bundle\ApiBundle\Processor\Config\Shared\NormalizeFilters
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get_config, configSection: filters, priority: -50 }
            - { name: oro.api.processor, action: get_field_config, configSection: filters, priority: -50 }
            - { name: oro.api.processor, action: get_relation_config, configSection: filters, priority: -50 }
