services:
    oro_api.get_relation_config.processor:
        class: Oro\Bundle\ApiBundle\Processor\RelationConfigProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - get_relation_config

    oro_api.get_relation_config.load_from_config_bag:
        class: Oro\Bundle\ApiBundle\Processor\GetRelationConfig\LoadFromConfigBag
        arguments:
            - @oro_api.config_bag
            - @oro_entity.entity_hierarchy_provider.all
        tags:
            - { name: oro.api.processor, action: get_relation_config, priority: -10 }

    oro_api.get_relation_config.load_from_metadata:
        class: Oro\Bundle\ApiBundle\Processor\GetRelationConfig\LoadFromMetadata
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get_relation_config, priority: -20 }
