services:
    oro_api.build_config.processor:
        class: Oro\Bundle\ApiBundle\Processor\BuildConfigProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - build_config

    oro_api.get_config.metadata:
        class: Oro\Bundle\ApiBundle\Processor\BuildConfig\BuildDefinition
        arguments:
            - @oro_entity.doctrine_helper
        tags:
            - { name: oro.api.processor, action: build_config, priority: -10 }
