services:
    oro_api.get_field_config.processor:
        class: Oro\Bundle\ApiBundle\Processor\Config\FieldConfigProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - get_field_config

    oro_api.get_field_config.load_from_metadata:
        class: Oro\Bundle\ApiBundle\Processor\Config\GetFieldConfig\LoadFromMetadata
        tags:
            - { name: oro.api.processor, action: get_field_config, priority: -20 }
