services:
    oro_api.build_config.processor:
        class: Oro\Bundle\ApiBundle\Processor\Config\ConfigProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - build_config

    oro_api.build_config.definition:
        class: Oro\Bundle\ApiBundle\Processor\Config\BuildConfig\BuildDefinition
        tags:
            - { name: oro.api.processor, action: build_config, priority: -10 }

    oro_api.build_config.filters:
        class: Oro\Bundle\ApiBundle\Processor\Config\BuildConfig\BuildFilters
        tags:
            - { name: oro.api.processor, action: build_config, requestAction: get_list, priority: -10 }
