parameters:
    # a list of supported formats of REST API requests based on JSON API delimited by |
    oro_api.rest_json_api.formats: json
    # default format of REST API requests based on JSON API
    oro_api.rest_json_api.default_format: json

services:
    oro_api.action_processor_bag:
        class: Oro\Bundle\ApiBundle\Processor\ActionProcessorBag

    oro_api.processor_bag:
        class: Oro\Component\ChainProcessor\ProcessorBag
        public: false
        arguments:
            - @oro_api.processor_factory

    oro_api.processor_factory:
        class: Oro\Component\ChainProcessor\ChainProcessorFactory
        public: false
        calls:
            - [addFactory, [@oro_api.simple_processor_factory, 10]]
            - [addFactory, [@oro_api.di_processor_factory]]

    oro_api.simple_processor_factory:
        class: Oro\Component\ChainProcessor\SimpleProcessorFactory
        public: false

    oro_api.di_processor_factory:
        class: Oro\Component\ChainProcessor\DependencyInjection\ProcessorFactory
        public: false
        arguments:
            - @service_container

    oro_api.doctrine_helper:
        class: Oro\Bundle\ApiBundle\Util\DoctrineHelper
        public: false
        arguments:
            - @doctrine

    oro_api.entity_accessor:
        class: Oro\Component\EntitySerializer\EntityDataAccessor
        public: false

    oro_api.entity_metadata_factory:
        class: Oro\Bundle\ApiBundle\Metadata\EntityMetadataFactory
        public: false
        arguments:
            - @oro_api.doctrine_helper

    oro_api.value_normalizer:
        class: Oro\Bundle\ApiBundle\Request\ValueNormalizer
        public: false
        arguments:
            - @oro_api.normalize_value.processor

    oro_api.object_normalizer:
        class: Oro\Bundle\ApiBundle\Normalizer\ObjectNormalizer
        public: false
        arguments:
            - @oro_api.doctrine_helper
            - @oro_api.entity_accessor
        calls:
            - [addNormalizer, [@oro_api.search_item_normalizer, 50]]
            - [addNormalizer, [@oro_api.datetime_normalizer]]

    oro_api.datetime_normalizer:
        class: Oro\Bundle\ApiBundle\Normalizer\DateTimeNormalizer
        public: false

    oro_api.search_item_normalizer:
        class: Oro\Bundle\ApiBundle\Normalizer\SearchItemNormalizer
        public: false

    oro_api.config_bag:
        class: Oro\Bundle\ApiBundle\Provider\ConfigBag
        public: false
        arguments:
            - []

    oro_api.config_provider:
        class: Oro\Bundle\ApiBundle\Provider\ConfigProvider
        arguments:
            - @oro_api.get_config.processor

    oro_api.metadata_provider:
        class: Oro\Bundle\ApiBundle\Provider\MetadataProvider
        arguments:
            - @oro_api.get_metadata.processor

    oro_api.field_config_provider:
        class: Oro\Bundle\ApiBundle\Provider\FieldConfigProvider
        arguments:
            - @oro_api.get_field_config.processor

    oro_api.relation_config_provider:
        class: Oro\Bundle\ApiBundle\Provider\RelationConfigProvider
        arguments:
            - @oro_api.get_relation_config.processor

    oro_api.entity_exclusion_provider:
        class: Oro\Bundle\EntityBundle\Provider\ChainExclusionProvider
        public: false

    oro_api.virtual_field_provider:
        class: Oro\Bundle\EntityBundle\Provider\ChainVirtualFieldProvider

    oro_api.entity_serializer:
        class: Oro\Component\EntitySerializer\EntitySerializer
        public: false
        arguments:
            - @oro_api.entity_serializer.doctrine_helper
            - @oro_api.entity_accessor
            - @oro_api.entity_serializer.data_transformer
            - @oro_api.entity_serializer.query_factory
            - @oro_api.entity_serializer.field_accessor
            - @oro_api.entity_serializer.config_normalizer
            - @oro_api.entity_serializer.data_normalizer

    oro_api.entity_serializer.doctrine_helper:
        class: Oro\Component\EntitySerializer\DoctrineHelper
        public: false
        arguments:
            - @doctrine

    oro_api.entity_serializer.query_factory:
        class: Oro\Component\EntitySerializer\QueryFactory
        public: false
        arguments:
            - @oro_api.entity_serializer.doctrine_helper
            - @oro_entity.query_hint_resolver

    oro_api.entity_serializer.field_accessor:
        class: Oro\Component\EntitySerializer\FieldAccessor
        public: false
        arguments:
            - @oro_api.entity_serializer.doctrine_helper
            - @oro_api.entity_accessor

    oro_api.entity_serializer.config_normalizer:
        class: Oro\Component\EntitySerializer\ConfigNormalizer
        public: false

    oro_api.entity_serializer.data_normalizer:
        class: Oro\Component\EntitySerializer\DataNormalizer
        public: false

    oro_api.entity_serializer.data_transformer:
        class: Oro\Component\EntitySerializer\EntityDataTransformer
        public: false
        arguments:
            - @service_container

    oro_api.rest_json_api.routing_options_resolver:
        class: Oro\Bundle\ApiBundle\Routing\RestJsonApiRouteOptionsResolver
        public: false
        arguments:
            - @oro_entity_config.entity_manager_bag
            - @oro_api.entity_exclusion_provider
            - @oro_entity.entity_alias_resolver
            - @oro_api.doctrine_helper
            - @oro_api.value_normalizer
            - %oro_api.rest_json_api.formats%
            - %oro_api.rest_json_api.default_format%
        tags:
            - { name: routing.options_resolver, priority: -255 }

    oro_api.rest_json_api.doc_handler:
        class: Oro\Bundle\ApiBundle\Routing\RestJsonApiDocHandler
        public: false
        arguments:
            - @oro_api.action_processor_bag
            - @oro_entity.entity_class_name_provider
            - @oro_entity.entity_alias_resolver
            - @oro_api.doctrine_helper
            - @oro_api.value_normalizer
        tags:
            - { name: nelmio_api_doc.extractor.handler }

    oro.api.filter_factory:
        class: Oro\Bundle\ApiBundle\Filter\ChainFilterFactory
        public: false

    oro.api.filter_factory.default:
        class: Oro\Bundle\ApiBundle\Filter\SimpleFilterFactory
        public: false
        calls:
            - [addFilter, [ 'integer', 'Oro\Bundle\ApiBundle\Filter\ComparisonFilter'] ]
            - [addFilter, [ 'unsignedInteger', 'Oro\Bundle\ApiBundle\Filter\ComparisonFilter'] ]
            - [addFilter, [ 'string', 'Oro\Bundle\ApiBundle\Filter\ComparisonFilter'] ]
            - [addFilter, [ 'boolean', 'Oro\Bundle\ApiBundle\Filter\ComparisonFilter'] ]
            - [addFilter, [ 'datetime', 'Oro\Bundle\ApiBundle\Filter\ComparisonFilter'] ]
            - [addFilter, [ 'entityAlias', 'Oro\Bundle\ApiBundle\Filter\ComparisonFilter'] ]
            - [addFilter, [ 'entityPluralAlias', 'Oro\Bundle\ApiBundle\Filter\ComparisonFilter'] ]
        tags:
            - { name: oro.api.filter_factory, priority: -10 }
