oro_api:
    actions:
        get_list:
            processor: oro_api.get_list.processor
            context_class: Oro\Bundle\ApiBundle\Processor\GetList\GetListContext
            processing_groups:
                initialize:
                    priority: -10
                security_check:
                    priority: -20
                build_query:
                    priority: -30
                load_data:
                    priority: -40
                normalize_data:
                    priority: -50
                finalize:
                    priority: -80
        get:
            processor: oro_api.get.processor
            context_class: Oro\Bundle\ApiBundle\Processor\Get\GetContext
            processing_groups:
                initialize:
                    priority: -10
                security_check:
                    priority: -20
                build_query:
                    priority: -30
                load_data:
                    priority: -40
                normalize_data:
                    priority: -50
                finalize:
                    priority: -60
