security:
    firewalls:
        api_wsse_secured:
            pattern: ^/api/.*
            wsse:
                lifetime: 3600
                realm:    "Secured API"
                profile:  "UsernameToken"
            context: main

oro_api:
    actions:
        get_list:
            processing_groups:
                initialize:
                    priority: -10
                security_check:
                    priority: -20
                build_query:
                    priority: -30
                load_data:
                    priority: -40
                normalize_data:
                    priority: -50
                finalize:
                    priority: -80
        get:
            processing_groups:
                initialize:
                    priority: -10
                security_check:
                    priority: -20
                build_query:
                    priority: -30
                load_data:
                    priority: -40
                normalize_data:
                    priority: -50
                finalize:
                    priority: -60
