oro_rest_api:
    resource: Oro\Bundle\ApiBundle\Controller\RestApiController
    type: rest
    prefix: api/
    requirements:
        version:  latest|v(\d+(\.\d+)*)
    defaults:
        version:  latest
