oro_rest_api_cget:
    path: /api/{version}/{entity}.{_format}
    methods: [GET]
    defaults:
        _controller: OroApiBundle:RestApi:cget
        _action: get_list
    options:
        group: rest_api

oro_rest_api_get:
    path: /api/{version}/{entity}/{id}.{_format}
    methods: [GET]
    defaults:
        _controller: OroApiBundle:RestApi:get
        _action: get
    options:
        group: rest_api
